[package]
name = "rosu-pp-native"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
name = "rosu_pp_native"
crate-type = ["cdylib"]

[dependencies]
rosu-pp = { git = "https://github.com/MaxOhn/rosu-pp", rev = "27a67242cad155a2767f5a25a423ca4ec3e3c274", version = "=4.0.1" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
